[pytest]

addopts = -v

testpaths = tests

markers =
    smoke: Smoke tests
    functional: Functional tests
    regression: Regression tests
    integration: Integration tests
    system: System tests
    e2e: End-to-end tests
    api: API tests